version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ShoppingManager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5434:5432"
    networks:
      - my-network
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - db
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
networks:
  my-network:
    driver: bridge